-- Gatherly Oracle SQL*Plus schema
-- Run this ONCE while connected to the application schema.
-- Example: sqlplus system/<password>@localhost:1521/FREEPDB1

-- Accounts are created by the application. Public registration can only create USER.
-- Project-specific name avoids conflict with an existing USERS table.
CREATE TABLE gatherlyusers (
    user_id       NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    full_name     VARCHAR2(120) NOT NULL,
    email         VARCHAR2(180) NOT NULL UNIQUE,
    password_hash VARCHAR2(64)  NOT NULL, -- SHA-256 hash used by the current raw-Java server
    role          VARCHAR2(20)  DEFAULT 'USER' NOT NULL
        CHECK (role IN ('USER', 'ADMIN', 'EVENT_MANAGER')),
    created_at    TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL
);

CREATE TABLE events (
    event_id    NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title       VARCHAR2(180) NOT NULL,
    description CLOB NOT NULL,
    event_date  TIMESTAMP NOT NULL,
    venue       VARCHAR2(180) NOT NULL,
    address     VARCHAR2(350) NOT NULL,
    latitude    NUMBER(10,7) NOT NULL,
    longitude   NUMBER(10,7) NOT NULL,
    price       NUMBER(12,2) NOT NULL CHECK (price >= 0),
    image_url   VARCHAR2(500),
    status      VARCHAR2(20) DEFAULT 'PUBLISHED' NOT NULL
        CHECK (status IN ('DRAFT', 'PUBLISHED', 'CANCELLED')),
    created_by  NUMBER NOT NULL REFERENCES gatherlyusers(user_id),
    created_at  TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL
);

CREATE TABLE orders (
    order_id       NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id        NUMBER NOT NULL REFERENCES gatherlyusers(user_id),
    event_id       NUMBER NOT NULL REFERENCES events(event_id) ON DELETE CASCADE,
    quantity       NUMBER(4) NOT NULL CHECK (quantity > 0),
    total_amount   NUMBER(12,2) NOT NULL CHECK (total_amount >= 0),
    status         VARCHAR2(20) DEFAULT 'PENDING' NOT NULL
        CHECK (status IN ('PENDING', 'PAID', 'FAILED', 'CANCELLED')),
    transaction_id VARCHAR2(100),
    created_at     TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL
);

CREATE TABLE payments (
    payment_id    NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id      NUMBER NOT NULL REFERENCES orders(order_id) ON DELETE CASCADE,
    gateway       VARCHAR2(30) NOT NULL,
    validation_id VARCHAR2(120),
    amount        NUMBER(12,2) NOT NULL CHECK (amount >= 0),
    status        VARCHAR2(20) NOT NULL,
    paid_at       TIMESTAMP
);

-- These indexes keep the most common reads fast.
CREATE INDEX idx_events_date ON events(event_date);
CREATE INDEX idx_orders_user ON orders(user_id);
CREATE INDEX idx_orders_event ON orders(event_id);

-- Bootstrap only the FIRST Admin after registering that account in the web app.
-- Later, logged-in Admin users create Admin/Event Manager accounts in the dashboard.
-- UPDATE gatherlyusers SET role = 'ADMIN' WHERE email = 'your-admin-email@example.com';
-- COMMIT;
